### ISSUE TITLE
能否分享一下文件划分的txt

### ISSUE THREAD

**Issue by skyABB** [ccq195/SketchTrans#1]
作者你好，非常感谢你的工作，但是我运行你的代码并不能生成划分数据集的txt

**Comment by Maximilian1794** [comment]
在datasets文件夹下有一个pku-processing.py的文件，那个就是处理数据集并生成txt的代码

**Comment by skyABB** [comment]
谢谢，已解决

**Comment by skyABB** [comment]
但是ChairV2和Shoev2得到train_visible.txt，train_sketch.txt这些是如何得到的，我尝试读取文件名称，但是不怎么正确
